### ISSUE TITLE
Error when importing an API into Microgateway from WSO2 API Manager

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-microgateway#815] opened 2019-09-25 12:32 UTC
### Description:
An error arises when trying to import an API from WSO2 API Manager into MIcrogateway when executing the import command shown below.

![image](https://user-images.githubusercontent.com/32578617/65599988-c09ef780-dfbc-11e9-9acb-4fd53ae82d23.png)

The error log is as follows:
![image](https://user-images.githubusercontent.com/32578617/65600020-d8767b80-dfbc-11e9-8a4c-454097d2e5dd.png)

### Steps to reproduce:
Entering the following two commands will reproduce the issue.

**micro-gw init eticketing**

**micro-gw import -a eTicketing -v 1.0.0 eticketing**

### Affected Product Version:

3.0.1

### OS and other environment details and versions:
- OS: Ubuntu 18.04.2 LTS
- Client: 
- Env (Docker/K8s): Binary

---

**Comment by praminda** [comment] 2020-01-24 10:49
Duplicate of #818

**Closed by praminda** 2020-01-24 10:49 UTC
Labels: Priority/Normal, Type/Bug
