### ISSUE TITLE
Adapter component becomes unresponsive intermittently

### ISSUE THREAD

**Issue by vlgunarathne** [wso2/product-microgateway#1981] opened 2021-04-29 08:22 UTC
### Description:
The adapter component becomes unresponsive intermittently and hence in turn newly published APIs return a HTTP 404 once invoked. We recover this by killing the adapter pod. After killing it, the APIs get synced to the router and works fine.

Following are the logs of the three components.

#### Router
```
[2021-04-29 04:51:58.499][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] StreamAggregatedResources gRPC config stream closed: 13,
[2021-04-29 04:51:58.812][1][info][upstream] [source/common/upstream/cds_api_impl.cc:71] cds: add 264 cluster(s), remove 11 cluster(s)
[2021-04-29 04:51:58.814][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterSand_header_based_routing_p20e31.0.0'
[2021-04-29 04:51:58.815][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterSand_cypresstestapp1.0.0'
[2021-04-29 04:51:58.816][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterSand_service_orchestratio_toqd1.0.0'
[2021-04-29 04:51:58.825][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterSand_AnotherHttpBin132541.0.0'
[2021-04-29 04:51:58.826][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterProd_HelloWorld1.0.0'
[2021-04-29 04:51:58.827][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterProd_breakingtest1321.0.0'
[2021-04-29 04:51:58.836][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterProd_AnotherHttpBin132541.0.0'
[2021-04-29 04:51:58.837][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterSand_breakingtest1321.0.0'
[2021-04-29 04:51:58.838][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterProd_cypresstestapp1.0.0'
[2021-04-29 04:51:58.847][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterSand_e2etest_api_dv_devportal1.0.0'
[2021-04-29 04:51:58.855][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterProd_mockySample21.0.0'
[2021-04-29 04:51:58.856][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterSand_HelloWorld1.0.0'
[2021-04-29 04:51:58.865][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterSand_mockySample21.0.0'
[2021-04-29 04:51:58.874][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterProd_e2etest_api_dv_devportal1.0.0'
[2021-04-29 04:51:58.884][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterProd_NewRandomAPI1239871.0.0'
[2021-04-29 04:51:58.885][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterProd_header_based_routing_p20e31.0.0'
[2021-04-29 04:51:58.887][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterProd_service_orchestratio_toqd1.0.0'
[2021-04-29 04:51:58.896][1][info][upstream] [source/common/upstream/cds_api_impl.cc:86] cds: add/update cluster 'clusterSand_NewRandomAPI1239871.0.0'
[2021-04-29 04:51:58.896][1][info][upstream] [source/common/upstream/cluster_manager_impl.cc:691] removing cluster clusterSand_service_orchestratio_97cmo1.0.0
[2021-04-29 04:51:58.896][1][info][upstream] [source/common/upstream/cds_api_impl.cc:97] cds: remove cluster 'clusterSand_service_orchestratio_97cmo1.0.0'
[2021-04-29 04:51:58.896][1][info][upstream] [source/common/upstream/cluster_manager_impl.cc:691] removing cluster clusterSand_mockytest2chathuranga1.0.0
[2021-04-29 04:51:58.896][1][info][upstream] [source/common/upstream/cds_api_impl.cc:97] cds: remove cluster 'clusterSand_mockytest2chathuranga1.0.0'
[2021-04-29 04:51:58.896][1][info][upstream] [source/common/upstream/cluster_manager_impl.cc:691] removing cluster clusterProd_service_orchestratio_rsmx1.0.0
[2021-04-29 04:51:58.896][1][info][upstream] [source/common/upstream/cds_api_impl.cc:97] cds: remove cluster 'clusterProd_service_orchestratio_rsmx1.0.0'
[2021-04-29 04:51:58.896][1][info][upstream] [source/common/upstream/cluster_manager_impl.cc:691] removing cluster clusterSand_service_orchestratio_rsmx1.0.0
[2021-04-29 04:51:58.896][1][info][upstream] [source/common/upstream/cds_api_impl.cc:97] cds: remove cluster 'clusterSand_service_orchestratio_rsmx1.0.0'
[2021-04-29 04:51:58.896][1][info][upstream] [source/common/upstream/cluster_manager_impl.cc:691] removing cluster clusterProd_service_orchestratio_97cmo1.0.0
[2021-04-29 04:51:58.897][1][info][upstream] [source/common/upstream/cds_api_impl.cc:97] cds: remove cluster 'clusterProd_service_orchestratio_97cmo1.0.0'
[2021-04-29 04:51:58.897][1][info][upstream] [source/common/upstream/cluster_manager_impl.cc:691] removing cluster clusterProd_mockytest2chathuranga1.0.0
[2021-04-29 04:51:58.897][1][info][upstream] [source/common/upstream/cds_api_impl.cc:97] cds: remove cluster 'clusterProd_mockytest2chathuranga1.0.0'
```

#### Enforcer Logs
```
2021-04-29 04:51:58,508 grpc-default-executor-47 ERROR Unable to create directory /logs
2021-04-29 04:51:58,512 grpc-default-executor-46 ERROR Unable to create directory /logs
[2021-04-29 04:51:58,503] ERROR - ApiListDiscoveryClient Error occurred during Api list discovery
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
at io.grpc.Status.asRuntimeException(Status.java:533) ~[org.wso2.choreo.connect.enforcer-0.9.0-alpha2.jar:0.9.0-alpha2]
at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) [org.wso2.choreo.connect.enforcer-0.9.0-alpha2.jar:0.9.0-alpha2]
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:413) [org.wso2.choreo.connect.enforcer-0.9.0-alpha2.jar:0.9.0-alpha2]
at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) [org.wso2.choreo.connect.enforcer-0.9.0-alpha2.jar:0.9.0-alpha2]
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742) [org.wso2.choreo.connect.enforcer-0.9.0-alpha2.jar:0.9.0-alpha2]
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:721) [org.wso2.choreo.connect.enforcer-0.9.0-alpha2.jar:0.9.0-alpha2]
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [org.wso2.choreo.connect.enforcer-0.9.0-alpha2.jar:0.9.0-alpha2]
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [org.wso2.choreo.connect.enforcer-0.9.0-alpha2.jar:0.9.0-alpha2]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
at java.lang.Thread.run(Unknown Source) [?:?]
[2021-04-29 04:51:58,505] ERROR - ApplicationDiscoveryClient Error occurred during Application discovery
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
```

#### Adapter
```
4/29/2021, 6:07:12.632 AM	dev-choreo-apim	stderr	2021/04/29 06:07:12 http: TLS handshake error from 172.20.2.41:50948: EOF	73bb610d-1281-4e81-8f8f-9b6588afd5ac/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 6:07:12.632 AM	dev-choreo-apim	stderr	2021/04/29 06:07:12 http: TLS handshake error from 172.20.2.41:50948: EOF	73bb610d-1281-4e81-8f8f-9b6588afd5ac/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 6:07:12.632 AM	dev-choreo-apim	stderr	2021/04/29 06:07:12 http: TLS handshake error from 172.20.2.41:50948: EOF	73bb610d-1281-4e81-8f8f-9b6588afd5ac/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 6:07:12.632 AM	dev-choreo-apim	stderr	2021/04/29 06:07:12 http: TLS handshake error from 172.20.2.41:50948: EOF	73bb610d-1281-4e81-8f8f-9b6588afd5ac/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 6:07:12.632 AM	dev-choreo-apim	stderr	2021/04/29 06:07:12 http: TLS handshake error from 172.20.2.41:50948: EOF	73bb610d-1281-4e81-8f8f-9b6588afd5ac/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 6:07:12.632 AM	dev-choreo-apim	stderr	2021/04/29 06:07:12 http: TLS handshake error from 172.20.2.41:50948: EOF	73bb610d-1281-4e81-8f8f-9b6588afd5ac/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 6:07:12.632 AM	dev-choreo-apim	stderr	2021/04/29 06:07:12 http: TLS handshake error from 172.20.2.41:50948: EOF	73bb610d-1281-4e81-8f8f-9b6588afd5ac/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 6:07:12.632 AM	dev-choreo-apim	stderr	2021/04/29 06:07:12 http: TLS handshake error from 172.20.2.41:50948: EOF	73bb610d-1281-4e81-8f8f-9b6588afd5ac/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 6:07:12.632 AM	dev-choreo-apim	stderr	2021/04/29 06:07:12 http: TLS handshake error from 172.20.2.41:50948: EOF	73bb610d-1281-4e81-8f8f-9b6588afd5ac/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 6:07:12.632 AM	dev-choreo-apim	stderr	2021/04/29 06:07:12 http: TLS handshake error from 172.20.2.41:50948: EOF	73bb610d-1281-4e81-8f8f-9b6588afd5ac/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 6:07:12.632 AM	dev-choreo-apim	stderr	2021/04/29 06:07:12 http: TLS handshake error from 172.20.2.41:50948: EOF	73bb610d-1281-4e81-8f8f-9b6588afd5ac/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 4:02:11.743 AM	dev-choreo-apim	stderr	2021/04/29 04:02:11 http: TLS handshake error from 172.20.2.102:43058: EOF	da4444ff-00df-4597-9f14-8ad110f4344e/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 4:02:11.743 AM	dev-choreo-apim	stderr	2021/04/29 04:02:11 http: TLS handshake error from 172.20.2.102:43058: EOF	da4444ff-00df-4597-9f14-8ad110f4344e/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 4:02:11.743 AM	dev-choreo-apim	stderr	2021/04/29 04:02:11 http: TLS handshake error from 172.20.2.102:43058: EOF	da4444ff-00df-4597-9f14-8ad110f4344e/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 4:02:11.743 AM	dev-choreo-apim	stderr	2021/04/29 04:02:11 http: TLS handshake error from 172.20.2.102:43058: EOF	da4444ff-00df-4597-9f14-8ad110f4344e/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 4:02:11.743 AM	dev-choreo-apim	stderr	2021/04/29 04:02:11 http: TLS handshake error from 172.20.2.102:43058: EOF	da4444ff-00df-4597-9f14-8ad110f4344e/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 4:02:11.743 AM	dev-choreo-apim	stderr	2021/04/29 04:02:11 http: TLS handshake error from 172.20.2.102:43058: EOF	da4444ff-00df-4597-9f14-8ad110f4344e/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 4:02:11.743 AM	dev-choreo-apim	stderr	2021/04/29 04:02:11 http: TLS handshake error from 172.20.2.102:43058: EOF	da4444ff-00df-4597-9f14-8ad110f4344e/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 4:02:11.743 AM	dev-choreo-apim	stderr	2021/04/29 04:02:11 http: TLS handshake error from 172.20.2.102:43058: EOF	da4444ff-00df-4597-9f14-8ad110f4344e/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 4:02:11.743 AM	dev-choreo-apim	stderr	2021/04/29 04:02:11 http: TLS handshake error from 172.20.2.102:43058: EOF	da4444ff-00df-4597-9f14-8ad110f4344e/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 4:02:11.743 AM	dev-choreo-apim	stderr	2021/04/29 04:02:11 http: TLS handshake error from 172.20.2.102:43058: EOF	da4444ff-00df-4597-9f14-8ad110f4344e/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 4:02:11.743 AM	dev-choreo-apim	stderr	2021/04/29 04:02:11 http: TLS handshake error from 172.20.2.102:43058: EOF	da4444ff-00df-4597-9f14-8ad110f4344e/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 4:02:11.743 AM	dev-choreo-apim	stderr	2021/04/29 04:02:11 http: TLS handshake error from 172.20.2.102:43058: EOF	da4444ff-00df-4597-9f14-8ad110f4344e/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 4:02:11.743 AM	dev-choreo-apim	stderr	2021/04/29 04:02:11 http: TLS handshake error from 172.20.2.102:43058: EOF	da4444ff-00df-4597-9f14-8ad110f4344e/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 4:02:11.743 AM	dev-choreo-apim	stderr	2021/04/29 04:02:11 http: TLS handshake error from 172.20.2.102:43058: EOF	da4444ff-00df-4597-9f14-8ad110f4344e/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "choreo-connect-adapter", "kapp.k14s.io/app": "1588768694271977160", "kapp.k14s.io/association": "v1.bb2320ae07ff46bb78500e9c6b5c5b7a", "pod-template-hash": "c9db45656" } ]	
4/29/2021, 4:02:11.743 AM	dev-choreo-apim	stderr	2021/04/29 04:02:11 http: TLS handshake error from 172.20.2.102:43058: EOF	da4444ff-00df-4597-9f14-8ad110f4344e/choreo-connect-adapter	[ { "app": "dev-choreo-control-plane", "choreo.component": "chor
```

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---
#### Suggested Labels:
Priority/Highest

**Comment by vlgunarathne** [comment] 2021-04-29 15:37
Please find the requested logs

[mgw-enforcer.log](https://github.com/wso2/product-microgateway/files/6399870/mgw-enforcer.log)
[mgw-router.log](https://github.com/wso2/product-microgateway/files/6399871/mgw-router.log)

**Comment by manjulaRathnayaka** [comment] 2021-04-30 09:36
@Rajith90 when can we expect a fix for this issue? I could not find from the project dashboards anyone working on this issue.

**Comment by Rajith90** [comment] 2021-05-01 13:08
We could not reproduce the issue as of now. Agreed to deploy the 0.9.0 pack and check with the newly added health endpoint  of the adapter to identify whether the gRPC service used for adapter and router communication is failing. I think further we might need new patch release with debug logs for the adapter and router xds communication

**Comment by manjulaRathnayaka** [comment] 2021-05-03 04:12
@vlgunarathne AFAIK, this issue is occurring in the dev environment frequently and it is identified as a blocker for test case development task.

**Comment by pubudu538** [comment] 2021-11-15 16:54
This is already fixed in the latest version. Hence closing the issue.

**Closed by pubudu538** 2021-11-15 16:54 UTC
Labels: Type/Bug, Priority/Highest, Choreo
