### ISSUE TITLE
[Build Issue] Strange build output in Windows and Unable to run the Micro-gateway

### ISSUE THREAD

**Issue by jrathnayake** [wso2/product-microgateway#811] opened 2019-09-24 10:44 UTC
I have a Windows 10 environment with Micro-gateway 3.0.1 binary. I have set the PATH for both Toolkit and Micro-gateway location.

No additional ballerina installed, hence "ballerina -v" gives below output:

D:\WSO2\mgw>ballerina -v
'ballerina' is not recognized as an internal or external command,
operable program or batch file.

I have created a new micro-gateway project using below command, and it was a success:
D:\WSO2\mgw>micro-gw init petstore
Project 'petstore' is initialized successfully.

I was trying to build the project using below command, and I get a strange output as shows below:
D:\WSO2\mgw>micro-gw build petstore
MICRO_GW_PROJECT_DIR:  "D:\WSO2\mgw"
Compiling source
    src:0.0.0

Running tests
    src:0.0.0
        No tests found

Generating executable
    ./target/D:\WSO2\mgw\petstore\target\petstore.balx
[Only one main parameter allowed but found several: "petstore" and "--compiled"]
Usage: micro-gw [command] [command options]
  Commands:
    help      display command help
      Usage: help [options] command

    init      initialize a new project
      Usage: init [options] project
        Options:
          -d, --deployment-config
            deployment-config file for docker/k8s
          -f, --force
            replace existing projects having same name
            Default: false
          --help, -h, ?
            print command help

    build      build a project
      Usage: build [options] project
        Options:
          -d, --deployment-config
            deployment-config file for docker/k8s
          --help, -h, ?
            print command help

    reset      reset configurations
      Usage: reset [options]
        Options:
          -c, --config
            external config file path

    import      pull APIs from API Publisher
      Usage: import [options] project
        Options:
          -a, --api-name
            name of the API
          --help, -h, ?
            print command help
          -k, --insecure
            skip ssl validation
            Default: false
          -l, --label
            gateway label
          -p, --password
            API Publisher password
          -s, --server-url
            API Publisher url
          -t, --truststore
            truststore for https connection
          -w, --truststore-pass
            truststore password
          -u, --username
            API Publisher username
          -v, --version
            version of the API

Looks like it generates the .balx file and I can see that in the folder. So I tried to run it using below command and I get the below error:
D:\WSO2\mgw\petstore\target>gateway petstore.balx
[Tue 09/24/2019 16:11:58.50] Starting Micro-Gateway
ballerina: HTTP access log enabled
ballerina: cannot find program file 'petstore.balx'

I have attached the access logfile from the Toolkit folder.
[microgw.log](https://github.com/wso2/product-microgateway/files/3646731/microgw.log)

**Comment by jrathnayake** [comment] 2019-09-24 13:12
I did some further modifications to the way we run the commands and came up with the below solution. 

Couldn't find an option to get rid of the wired message which comes during the build process. But, I managed to run the generated .balx file using the below command:
D:\WSO2\wso2ammicrogwwindows3.0.1\bin>gateway.bat D:/WSO2/mgw/petstore/target/petstore.balx

I navigated to the /bin directory of the micro-gateway binary and executed the gateway.bat (specified the .bat file extension) and gave the full path of the .balx file and it worked.

**Comment by praminda** [comment] 2019-09-25 10:29
@jrathnayake are you sure you don't have any other versions of mgw installed on your machine?
Run `echo %path%` command in a command prompt window and check if the path is set to a different version of the MGW.

I'm assuming this because, we no longer use `--compiled` flag in our executables. This flag was there in an pre release version of 3.0.1. So make sure you've installed 3.0.1 release version and only that version is available for your cmd.

**Comment by jrathnayake** [comment] 2019-09-25 17:25
Below is the output of the echo %path%

C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Microsoft MPI\Bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;D:\Program Files\Microsoft SQL Server\140\Tools\Binn\;D:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;D:\Program Files\Microsoft SQL Server\140\DTS\Binn\;D:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;d:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;D:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\dotnet\;D:\Program Files\Microsoft VS Code\bin;C:\Program Files\Java\jdk1.8.0_191\bin;D:\WSO2\APIManager\2.6.0\\bin;C:\Program Files\WUM\bin;D:\Program Files\Microsoft SQL Server\130\Tools\Binn\;D:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;D:\WSO2\EnterpriseIntegrator\6.5.0\bin;D:\WSO2\IdentityServer\5.8.0\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\MySQL\MySQL Server 8.0\bin;D:\WSO2\wso2ammicrogwtoolkit3.0.1\bin;D:\WSO2\wso2ammicrogwwindows3.0.1\bin;C:\Users\Joy\AppData\Local\Microsoft\WindowsApps;D:\Program Files\JetBrains\IntelliJ IDEA 2018.3.1\bin;;D:\Program Files\JetBrains\DataGrip 2018.3.4\bin;;C:\Program Files\Java\jdk1.8.0_191\;D:\WSO2\wso2ammicrogwtoolkit3.0.1\bin;D:\WSO2\wso2ammicrogwwindows3.0.1\bin;

As it shows, I don't have any other version of micro-gateway installed.

**Comment by praminda** [comment] 2019-09-27 03:38
Looks like there is an issue in the 3.0.1 toolkit's `.bat` executable. This has been already fixed in 3.0.2 branch. Fix will be available with the 3.02 toolkit release.
Thanks for reporting the issue 👍

**Comment by praminda** [comment] 2019-09-27 03:42
Duplicate of #660

**Closed by praminda** 2019-09-27 03:42 UTC
Labels: Priority/Normal, Resolution/Duplicate, Type/Question
