### ISSUE TITLE
Microgateway endpoint URL split at special character 

### ISSUE THREAD

**Issue by dinelka7** [wso2/product-microgateway#1203] opened 2020-04-21 06:23 UTC
### Description:

In microgateway 3.1.0, if a URL with query param is used for the endpoint URL, when calling for the enpoint, microgateway will break the URL at '&' character. It seems like URL is breaking after special character. 

### Steps to reproduce:
Create a microgateway project with endpoint URL similar to below.
https://postman-echo.com/post?foo1=bar1&foo2=bar2

Build and deploy in microgateway. When after invoking the API, below URL will be called as endpoint.
https://postman-echo.com/post?foo1&

### Affected Product Version:

microgateway 3.1.0

---

**Comment by praminda** [comment] 2020-04-22 10:15
Duplicate of #1207

**Comment by praminda** [comment] 2020-04-22 10:16
Refer to #1207 for progress and the discussion on the issue

**Comment by praminda** [comment] 2020-04-22 10:16
Refer to #1207 for progress and the discussion on the issue

**Closed by praminda** 2020-04-22 10:16 UTC
Labels: Priority/Normal, Type/Bug
