### ISSUE TITLE
Basic Authentication is not working

### ISSUE THREAD

**Issue by bhathiya** [wso2/product-microgateway#537] opened 2019-05-16 11:09 UTC
**Steps to reproduce:**

1) Create an API with the below OAS file.

```
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
x-mgw-basePath: /petstore/v1
x-mgw-throttling-tier: 5PerMin
x-mgw-production-endpoints: "#/x-mgw-endpoints/myEndpoint"
paths:
  /dogs:
    get:
      security: 
        - petstore_basic: []    
      x-mgw-production-endpoints: "#/x-mgw-endpoints/myEndpoint2"    
      x-mgw-throttling-tier: 2PerMin
      x-mgw-security-disable: false
      summary: List all pets
      operationId: listPets
      responses:
        '200':
          description: A paged array of pets
    post:
      security: 
        - petstore_oauth2: []  
      x-mgw-production-endpoints: "#/x-mgw-endpoints/myEndpoint2"
      summary: Create a pet
      operationId: createPets
      responses:
        '201':
          description: Null response
  /cats:
    get:
      security: 
        - petstore_jwt: []
      x-mgw-throttling-tier: 8PerMin
      summary: Info for a specific pet
      operationId: showPetById
      responses:
        '200':
          description: Expected response to a valid request
x-mgw-endpoints:
 - myEndpoint:
    urls:
    - http://www.mocky.io/v2/5cdc00d52d0000dc49f5a4e9
 - myEndpoint2:
    urls:
    - http://www.mocky.io/v2/5cdc45532d00008f14f5a6c9   
components:
  securitySchemes:
    petstore_oauth2:
      type: oauth2
      flows: 
        authorizationCode:
          authorizationUrl: https://this.is.a.dummy.url
          tokenUrl: https://this.is.a.dummy.url
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets  
    petstore_basic:
      type: http
      scheme: basic
    petstore_jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
```

2) Invoke `GET dogs` with basic authentication. It fails. (This should pass)

3) Invoke `GET dogs` with JWT authentication. It passes. (This should fail)

**Comment by Rajith90** [comment] 2019-05-17 08:53
@bhathiya 

> Invoke GET dogs with JWT authentication. It passes.
I could not reproduce this. It fails for me with error message
`{"fault":{"code":900917, "message":"Invalid Authentication scheme", "description":"Invalid Authentication scheme. API can not be used with this authentication scheme"}}`

Other scenario has been fixed with : https://github.com/wso2/product-microgateway/pull/539

**Closed** 2019-05-17 08:53 UTC
Labels: Affected/3.0.0-Beta, Priority/Highest, bug, dev-first
