### ISSUE TITLE
Introduce a Config Model for Filter Chain

### ISSUE THREAD

**Issue by menakaj** [wso2/product-microgateway#1462] opened 2020-11-02 06:03 UTC
### Describe your problem(s)
Filter chain should be able to configure by using a static configuration file.

### How will you implement it

---

**Comment by praminda** [comment] 2021-01-26 10:03
We no longer consider static config file based configuration for filter chain
Duplicate of #1452

**Closed by praminda** 2021-01-26 10:03 UTC
Labels: Priority/Normal, Type/New Feature, envoy-gw
