### ISSUE TITLE
Checkstyle failures only on windows

### ISSUE THREAD

**Issue by praminda** [wso2/product-microgateway#984] opened 2020-02-12 06:43 UTC
### Description:

There many checkstyle violations in the project. However these are not reported during the build on linux and mac machines. These errors are reported properly on windows during the build.

### Steps to reproduce:
1. Use windows and linux/mac machines.
1. `git clone` the mgw repo.
1. Run `mvn clean install` and observe the output.
1. Linux/Mac build is OK. But window build fails with checkstyle issues.

### Affected Product Version:

current master as of 14881f5
### Environment details (with versions):
- OS: Windows
- Client:
- Env (Docker/K8s): VM

**Comment by Rajith90** [comment] 2020-05-04 07:07
Duplicate of https://github.com/wso2/product-microgateway/issues/1219

**Closed by Rajith90** 2020-05-04 07:07 UTC
Labels: Priority/High, Type/Bug, good first issue
