### ISSUE TITLE
value of the "apiCreator" field is null when invoking the API without a token (APIM 3.0.0)

### ISSUE THREAD

**Issue by rizmir22** [wso2/product-microgateway#1166] opened 2020-03-23 15:32 UTC
### Description:

When we use the micro gateway 3.0.4 with analytics, we received the error when we invoked the API without a token. 
It seems the value of the "apiCreator" field has set to null when invoking the API without a token and it has caused this issue.

Tested toolkit version 3.0.4

### Steps to reproduce:
Configure the APIM 3.0 with analytics. 
Create an API and disable the token for a resource
Import the API to the Microgateway tool kit and build it.
Then run the micro gateway with the executable-file file. (please make sure you have enable the analytics in MGW)
Invoke the API without a token

### Affected Product Version:
3.0.4

### Environment details (with versions):
- OS: Linux
- Client: 
- Env (Docker/K8s):

---
#### Related Issues:
https://github.com/wso2/product-microgateway/issues/1055

#### Suggested Labels:
MGW 3.0.4

**Comment by AmaliMatharaarachchi** [comment] 2020-03-30 08:42
With mgw 3.1.0, this scenario works as expected without errors. However, this issue is reproducible in mgw 3.0.x

**Comment by Rajith90** [comment] 2020-05-21 14:50
Closing since fixed in the latest version of 3.1.0

**Closed by Rajith90** 2020-05-21 14:50 UTC
Labels: Priority/Normal, Type/Bug
