### ISSUE TITLE
Provide capability to disable the router accesslogs

### ISSUE THREAD

**Issue by VirajSalaka** [wso2/product-microgateway#1776] opened 2021-03-26 05:54 UTC
### Describe your problem(s)
Since the accesslogs can cause a performance hit, it is better to make it configurable.

### Describe your solution
use log_config.toml to provide enabled configuration.

### How will you implement it

---

**Comment by Rajith90** [comment] 2021-04-07 08:41
Duplicate of : https://github.com/wso2/product-microgateway/issues/1810

**Closed by Rajith90** 2021-04-07 08:41 UTC
Labels: Priority/Normal, Type/New Feature, envoy-gw
