### ISSUE TITLE
Importing API from WSO2 API Manager (3.0.0 Alpha2) not working

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-microgateway#823] opened 2019-09-30 09:21 UTC
### Description:

Importing API from WSO2 API Manager does not work with API Manager v3.0.0 Alpha2 pack. The error shown in the console is:
![image](https://user-images.githubusercontent.com/32578617/65865760-6e315280-e391-11e9-9752-22dea05b4c94.png)

The error shown in the microgateway log is:
![image](https://user-images.githubusercontent.com/32578617/65865890-90c36b80-e391-11e9-95bf-a8b579c278e3.png)

### Steps to reproduce:
- Initialize project
- Import API from API Manager

### OS and other environment details and versions:
- OS: Ubuntu 18.04.2 LTS
- Client:
- Env (Docker/K8s):

---

**Comment by praminda** [comment] 2020-01-24 10:48
Duplicate of #818

**Closed by praminda** 2020-01-24 10:48 UTC
Labels: Priority/Normal, Type/Bug
