### ISSUE TITLE
Import API from API-M 3.0.0 is not working.

### ISSUE THREAD

**Issue by joaoemilio** [wso2/product-microgateway#857] opened 2019-11-07 02:13 UTC
### Description:
Import API from API-M 3.0.2 is not working.
To workaround it you have to:

1. Change toolkit-config.toml to use REST API v0.15
2. Export new API-M 3.0 certificate from API-M/repository/resources/security/wso2carbon.jks
3. Rename/Remove alias "wso2carbon" from MicroGateway Toolkit ballerinaTruststore.p12
4. Import certificate from step #2 

Try again.

### Steps to reproduce:
Copyright (C) Microsoft Corporation. Todos os direitos reservados.
PS C:\wso2\demos\apim-3.0> C:\tools\wso2am-micro-gw-toolkit-3.0.2\bin\micro-gw.bat import -k -a mailbox -v 1.0.0 .\mailbox-api
Enter Username:
admin
Enter Password for admin:

Enter APIM base URL [https://localhost:9443]:

You are using REST version - v0.15 of API Manager. (If you want to change this, go to <MICROGW_HOME>/conf/toolkit-config.toml)
Enter Trust store location: [lib/platform/bre/security/ballerinaTruststore.p12]

Enter Trust store password: [ use default? ]

micro-gw: Error occurred while trying to connect with server. Is the server running at https://localhost:9443?

The error that is logged is the following:
`[2019-11-06 23:43:52,815] ERROR {org.wso2.apimgt.gateway.cli.cmd.Main} - Error occurred while communicate with DCR endpoint: https://localhost:9443/client-registration/v0.15/register 
org.wso2.apimgt.gateway.cli.exception.CLIRuntimeException: Error occurred while communicate with DCR endpoint: https://localhost:9443/client-registration/v0.15/register
	at org.wso2.apimgt.gateway.cli.oauth.OAuthServiceImpl.generateClientIdAndSecret(OAuthServiceImpl.java:142)
	at org.wso2.apimgt.gateway.cli.cmd.ImportCmd.execute(ImportCmd.java:246)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.wso2.apimgt.gateway.cli.cmd.Main.main(Main.java:48)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at org.wso2.apimgt.gateway.cli.oauth.OAuthServiceImpl.generateClientIdAndSecret(OAuthServiceImpl.java:117)
	... 3 more
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:352)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:260)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
	... 16 more
Caused by: java.security.cert.CertPathValidatorException: signature check failed
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:219)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:347)
	... 22 more
Caused by: java.security.SignatureException: Signature does not match.
	at sun.security.x509.X509CertImpl.verify(X509CertImpl.java:449)
	at sun.security.provider.certpath.BasicChecker.verifySignature(BasicChecker.java:166)
	at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:147)
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
	... 27 more`

### Affected Product Version:
Microgateway 3.0.2
API-M 3.0.0

### Environment details (with versions):
- OS: Windows 10
- Client: ?
- Env (Docker/K8s): Powershell

**Comment by praminda** [comment] 2019-11-07 15:35
@joaoemilio 
MGW 3.0.2 was released prior to APIM 3.0.0 release. Also its just a toolkit update release(patch release) for MGW 300 and should not be considered as a new release of complete MGW product itself.
So we don't claim the complete OOB compatibility with new APIM release with MGW 302. However next MGW product release 310 will have the OOB compatibility with MGW release. Hopefully we'll be able to make it compatible even before that with the MGW303 patch release.

**Comment by praminda** [comment] 2020-01-24 09:54
Resolved by #819 
Duplicate of #818

**Closed by praminda** 2020-01-24 09:54 UTC
Labels: Priority/Normal, Type/Bug
