### ISSUE TITLE
Cert passing to micro gateway level from ballerina 

### ISSUE THREAD

**Issue by amalkasubasinghe** [wso2/product-microgateway#1182] opened 2020-04-02 03:11 UTC
### Describe your problem(s)
We want to access cert from micro gateway runtime filters
We want to get this fixed on v3.1.0

### How will you implement it

---

**Comment by Rajith90** [comment] 2020-05-21 14:48
Duplicate of : https://github.com/wso2/product-microgateway/issues/1237

**Closed by Rajith90** 2020-05-21 14:48 UTC
Labels: Priority/Normal, Type/New Feature
