### ISSUE TITLE
Configuration file cannot take values with special character "#" 

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#321] opened 2019-03-07 06:02 UTC
**Description:**
micro-gw.conf values cannot be included "#". The reason behind this probably can be that it is read "#sometext" as a comment.

**Steps to reproduce:**
e.g.
In micro-gw.conf if we have a password that contains "#" special character as follows.

[keyManager]
password="pa#sword"

**Comment by praminda** [comment] 2019-03-29 04:41
@AmaliMatharaarachchi Can you specify the product version for the issue?

**Comment by AmaliMatharaarachchi** [comment] 2019-03-29 04:59
version 2.6.0 
But I think it is applicable to every other version which uses TOML configuration files.

**Comment by Rajith90** [comment] 2019-04-08 09:44
This seems to be a limitation in the toml format

**Comment by Rajith90** [comment] 2019-04-08 09:50
https://github.com/ballerina-platform/ballerina-lang/issues/9778

**Comment by praminda** [comment] 2019-06-03 08:30
Postponing the fix until ballerina team issues a fix for this

**Comment by praminda** [comment] 2019-09-05 08:22
This issue has been fixed in ballerina. Should be able to resolve this once the ballerina 1.0.0 migration is complete.

**Comment by praminda** [comment] 2019-09-16 09:30
Ballerina 1.0.0 migration can be tracked in #717

**Comment by praminda** [comment] 2020-01-16 04:05
@AmaliMatharaarachchi Shall we try this now. Should be fixed with the ballerina upgrade efforts

**Comment by praminda** [comment] 2020-02-05 04:08
Ballerina is now upgraded to 1.1.x and No longer reproducible in master branch as of 4aa807bc

**Closed by praminda** 2020-02-05 04:08 UTC
Labels: Affected/2.6.0, Priority/Normal, Type/Bug
