### ISSUE TITLE
Cannot stop micro-gateway background process in CentOS7/RHEL7

### ISSUE THREAD

**Issue by KosalaHerath** [wso2/product-microgateway#698] opened 2019-07-10 12:07 UTC
### Description:
Can not stop the micro-gateway background service after started in background. This issue only happen in centOS7 and RHEL7 systems. 
Root cause is these operating systems are not supporting "lsof" command in default. Install lsof package on the server using yum can be use as a solution.

### Steps to reproduce:
- Start the micro-gateway with following command as a background service.
`gateway start <path_to_balx_file>`
- This will start the server in background.
- Try to stop the server using following command.
`gateway stop`
- Then following error will show in the terminal.
`./gateway: line 138: lsof: command not found
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]`

### Affected Product Version:
- 3.0.1

### OS, DB, other environment details and versions:
- OS: CentOS7 and RHEL7

**Comment by VirajSalaka** [comment] 2020-03-11 09:31
I will be working on this issue.

**Comment by VirajSalaka** [comment] 2020-03-11 10:01
Tested with centos-7.7. Could not reproduce the issue.

**Comment by VirajSalaka** [comment] 2020-03-11 10:14
Tested with CentOS 7.7. Could not reproduce the issue. The reason could be that the gateway script does not contain the "lsof" command anymore.

**Comment by praminda** [comment] 2020-03-11 10:54
@VirajSalaka That should be the reason. We no longer look for access log process separately as we don't have it enabled by default.

**Comment by praminda** [comment] 2020-03-11 10:56
@KosalaHerath Closing the issue since this is no longer reproducible in 3.1.0-beta. Let us know if you have any comments.

**Closed by praminda** 2020-03-11 10:56 UTC
Labels: Affected/3.0.1, Priority/Normal, Type/Bug
