### ISSUE TITLE
Subscription unblocking does not works

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#1832] opened 2021-04-06 09:12 UTC
### Description:
Blocking and unblocking the subscription would still not allow the API to be accessed. 

### Steps to reproduce:
1. Block a subscription from publisher portal(click block production only)
2.  Then invoke , we will get below message.
```{"error_message":"The requested API is temporarily blocked","code":"900907","error_description":"User is NOT authorized to access the Resource. API Subscription validation failed."}```
3.  Then unblock ad invoke the API. It still does not allow and gives a different error message
```{"error_message":"Message blocked","code":"900805","error_description":"You have been blocked from accessing the resource"}```

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Rajith90** [comment] 2021-04-22 11:59
Re opening the issue since happening again in 0.9.0 post beta pack

**Comment by praminda** [comment] 2021-04-23 18:08
Tried multiple times with multiple options but couldn't reproduce.

**Comment by VirajSalaka** [comment] 2021-12-13 16:42
I managed to reproduce the issue. These steps needs to be added as well.
From Publisher portal, set the subscription to `block production only`.
Then restart the adapter and enforcer.
First try invoking the API with a valid token, you would notice that the first error response is recieved.
Then `Unblock the subscription`.
After all invoke the API, and you would notice that the second error message appear.

**Comment by VirajSalaka** [comment] 2021-12-13 16:48
The reason was that there is a blocking condition recieved during the startup. 
`/t/abc.com/myapi1/v1:v1:abc@abc.com-DefaultApplication:PRODUCTION`

When the subscription is unblocked, it simply updates the subscription List, but the blocking condition is not.
Hence it would result in the given behavior.

**Comment by VajiraPrabuddhaka** [comment] 2022-03-26 08:07
I tried the exact steps mentioned below, as well as the original steps, but it was unable to reproduce it.
> I managed to reproduce the issue. These steps needs to be added as well. From Publisher portal, set the subscription to `block production only`. Then restart the adapter and enforcer. First try invoking the API with a valid token, you would notice that the first error response is recieved. Then `Unblock the subscription`. After all invoke the API, and you would notice that the second error message appear.

Also checked whether any blocking conditions are receiving at the startup. Did not see any such conditions are receiving..


> The reason was that there is a blocking condition recieved during the startup. `/t/abc.com/myapi1/v1:v1:abc@abc.com-DefaultApplication:PRODUCTION`
> 
> When the subscription is unblocked, it simply updates the subscription List, but the blocking condition is not. Hence it would result in the given behavior.

Hence closing this issue..

**Closed by VajiraPrabuddhaka** 2022-03-26 08:07 UTC
Labels: Type/Bug, Priority/Normal
