### ISSUE TITLE
Add analytics filter

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#1512] opened 2020-12-02 06:24 UTC
### Describe your problem(s)

Add analytics to envoy based microgateway.

### How will you implement it

After authenticating and applying filters to the request via the filter chain, it will notify the envoy gateway with its decision through a gRPC message as we discussed earlier. We will pass along analytics related metadata along with this message. 
Once the upstream responds to the envoy gateway, a pre-build envoy extension will be used to asynchronously stream response details back to the filter chain. ALS (gRPC streaming service) is a gRPC streaming service that will asynchronously stream downstream connection details, time durations, http response, metadata, etc to the filter chain. Thereafter, the filter chain will calculate details required for analytics upon a response entry from the ALS. Then this filter chain will publish the data to the analytics server in the background.

Tasks

- [x] [Basic Implementation] Add Basic Analytics Filter #1741

- [x] [Improvements] Improvements to the Analytics Publishing #1742

---

**Comment by Rajith90** [comment] 2021-04-07 10:06
Duplicate of : https://github.com/wso2/product-microgateway/issues/1741

**Closed by Rajith90** 2021-04-07 10:06 UTC
Labels: Priority/Normal, Type/New Feature, envoy-gw
