### ISSUE TITLE
A user with ballerina 1.0.1 installed can't run Quick Start

### ISSUE THREAD

**Issue by joaoemilio** [wso2/product-microgateway#852] opened 2019-10-23 14:24 UTC
### Steps to reproduce:
MacBook-Joao:microgw-3.0.2 joaoemilio$ micro-gw build petstore
Compiling source
    src:0.0.0

Running tests
    src:0.0.0
	No tests found

Generating executable
    ./target//Users/joaoemilio/wso2/demos/microgw-3.0.2/petstore/target/petstore.balx
ballerina: Oh no, something really went wrong. Bad. Sad.

There should be a file named "ballerina-internal.log" in the current directory.
If you are able to share with us the code that broke Ballerina then
we would REALLY appreciate if you would report this to us:
go to https://github.com/ballerina-platform/ballerina-lang/issues and
create a bug report with both this log file and the sample code.

We thank you for helping make us better dancers.
MacBook-Joao:microgw-3.0.2 joaoemilio$ 

### Affected Product Version:
3.0.2

### Environment details (with versions):
- OS: Mac OS Mojave 10.14.6
- Client: 
- Env (Docker/K8s): Mac / Binary

**Comment by Rajith90** [comment] 2019-11-20 03:59
This issue was on 3.0.1 and was fixed in 3.0.2 version [1]. We could not reproduce this issue as well. Could you please attach the ballerina-inaternal.log file and also check whether the MICROGW_HOME is pointing to 3.0.2 not 3.0.1

[1] - https://github.com/wso2/product-microgateway/issues/810

**Comment by praminda** [comment] 2020-02-06 05:42
Hi @joaoemilio 
It looks like you are executing a previously installed MGW301 available in your `$PATH`. MGW302 build output should give you more information during the build process. Please try again after removing 301 from `$PATH`

**Closed by praminda** 2020-02-06 05:42 UTC
Labels: Priority/Normal, Type/Bug
